# Generated by Django 4.0.4 on 2022-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorpanel', '0002_doctorschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='averageconsultime',
            field=models.CharField(default='5 minutes', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='Timeavail',
            field=models.CharField(max_length=50),
        ),
    ]
