# Generated by Django 4.0.4 on 2022-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorpanel', '0003_doctorschedule_averageconsultime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorschedule',
            name='Timeavail',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='Endtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='Startime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='averageconsultime',
            field=models.IntegerField(default=5),
        ),
    ]
