# Generated by Django 4.0.4 on 2022-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorpanel', '0004_remove_doctorschedule_timeavail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='lastime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
