# Generated by Django 4.0.4 on 2022-05-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorpanel', '0007_alter_doctorschedule_averageconsultime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='averageconsultime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
