# Generated by Django 4.0.4 on 2022-05-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorpanel', '0010_alter_doctorschedule_averageconsultime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.CharField(max_length=50)),
                ('Doctor', models.CharField(max_length=50)),
                ('Medicines', models.JSONField()),
            ],
        ),
    ]
