# Generated by Django 4.0.4 on 2022-05-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorpanel', '0011_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
