# Generated by Django 4.0.4 on 2022-05-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient', models.CharField(max_length=50)),
                ('Doctor', models.CharField(max_length=50)),
            ],
        ),
    ]
