# Generated by Django 4.0.4 on 2022-05-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.TextField(blank=True, null=True)),
                ('dieases', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('operations', models.TextField(blank=True, null=True)),
                ('currentmedications', models.TextField(blank=True, null=True)),
                ('Exercise', models.CharField(blank=True, max_length=100, null=True)),
                ('Eating', models.CharField(blank=True, max_length=100, null=True)),
                ('Alcohol', models.CharField(blank=True, max_length=100, null=True)),
                ('smoke', models.CharField(blank=True, max_length=100, null=True)),
                ('Caffeine', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.patient')),
            ],
        ),
    ]
