# Generated by Django 4.0.4 on 2022-05-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
