# Generated by Django 4.0.4 on 2022-05-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
